project_name: AC
env: 测试环境
# 测试人员名称，作用于自动生成代码的作者，以及发送企业微信、钉钉通知的测试负责人
developer: zhengsx

# 域名1
host: https://blog.imky.ink
# 域名2，支持多个域名配置
host_secondary:

# 报告通知类型，0：不发送通知 1：钉钉 2：飞书通知 3：企业微信通知 4：邮箱通知
# 支持同时发送多个通知，逗号分割，如 1,2
notification_type: 0
# 收集失败的用例开关，整理成excel报告的形式，自动发送
excel_report: False

# 企业通知相关配置
ding_talk:
    webhook:
    secret:
lark:
    webhook:
wechat:
    webhook:
email:
    send_user:
    email_host:
    stamp_key:
    send_list:

# 数据库相关配置
mysql_db:
    host:
    user:
    password:
    port:
sqlite:
    address:
redis:
    host:
    port:
    password:
    decode_responses:
    db:

# 镜像源
mirror_source: http://mirrors.aliyun.com/pypi/simple/
